"""Added tag column

Revision ID: 41bf39d2c740
Revises: de189ae8627c
Create Date: 2020-12-30 19:24:34.514686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bf39d2c740'
down_revision = 'de189ae8627c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('tag', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'tag')
    # ### end Alembic commands ###
